/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.KhoaThiBLL;
import DTO.KhoaThiDTO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HAI HUONG
 */
public class KhoaThiGUI extends javax.swing.JPanel {
    DefaultTableModel table;
    /**
     * Creates new form KhoaThiGUI
     */
    public KhoaThiGUI() {
        initComponents();
        txtmkt.setEnabled(false);
        doDuLieuLenBang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmkt = new javax.swing.JTextField();
        txttkt = new javax.swing.JTextField();
        jdcDOB = new com.toedter.calendar.JDateChooser();
        jbtnthem = new javax.swing.JButton();
        jbtnxoa = new javax.swing.JButton();
        jbtnsua = new javax.swing.JButton();
        jbtnql = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSortTNV = new javax.swing.JTextField();
        jbnttimkiem = new javax.swing.JButton();
        jt = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("KHÓA THI");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã Khóa Thi:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tên Khóa Thi:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ngày bắt đầu thi:");

        jbtnthem.setBackground(new java.awt.Color(153, 255, 255));
        jbtnthem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnthem.setText("Thêm");
        jbtnthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnthemMouseClicked(evt);
            }
        });

        jbtnxoa.setBackground(new java.awt.Color(153, 255, 255));
        jbtnxoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnxoa.setText("Xóa");
        jbtnxoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnxoaMouseClicked(evt);
            }
        });

        jbtnsua.setBackground(new java.awt.Color(153, 255, 255));
        jbtnsua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnsua.setText("Sửa");
        jbtnsua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnsuaMouseClicked(evt);
            }
        });

        jbtnql.setBackground(new java.awt.Color(153, 255, 255));
        jbtnql.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnql.setText("Quay lại");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("--------Tìm Kiếm Khóa Thi--------");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tên Khóa Thi:");

        jbnttimkiem.setBackground(new java.awt.Color(153, 255, 255));
        jbnttimkiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbnttimkiem.setText("Tìm kiếm");
        jbnttimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbnttimkiemMouseClicked(evt);
            }
        });

        jt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Khóa Thi", "Ngày bắt đầu", "Tên Khóa Thi"
            }
        ));
        jt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt1MouseClicked(evt);
            }
        });
        jt.setViewportView(jt1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtSortTNV, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jbnttimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdcDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txttkt)
                            .addComponent(txtmkt))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtnsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnthem, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnql))))))
                .addContainerGap(111, Short.MAX_VALUE))
            .addComponent(jt)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmkt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txttkt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnql, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jdcDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSortTNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbnttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)))
                .addComponent(jt, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void setTextFields(String toString, String toString0, String toString1) {
        txtmkt.setText(toString);
        txttkt.setText(toString0);
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        try {
            jdcDOB.setDate(format.parse(toString1));
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(KhoaThiDTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
    }

    public void doDuLieuLenBang() {
        KhoaThiBLL bus = new KhoaThiBLL();
        try {
            bus.docDuLieu();
            table = (DefaultTableModel) jt1.getModel();
            table.setRowCount(0);
            for (KhoaThiDTO kh : bus.ds) {
                Vector vt = new Vector();
                vt.add(kh.getKhoathiid()); 
                DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                vt.add(format.format(kh.getNgaybatdau()));
                vt.add(kh.getTenkhoathi());
                table.addRow(vt);
            }
            jt1.setModel(table);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(KhoaThiDTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

     public void doDuLieuSearch(Map<String,String> map)
    {
        KhoaThiBLL bus = new KhoaThiBLL();
        try {
            bus.docduLieusearch(map);
            table = (DefaultTableModel) jt1.getModel();
            table.setRowCount(0);
            for(KhoaThiDTO kh : bus.ds)
            {
                Vector vt = new Vector();
                vt.add(kh.getKhoathiid());
                DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                vt.add(format.format(kh.getNgaybatdau()));
                vt.add(kh.getTenkhoathi());
                table.addRow(vt);
            }
            jt1.setModel(table);
        } catch (Exception ex) {
            Logger.getLogger(KhoaThiDTO.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     
    public void cleanView() //Xóa trắng các TextField
    {
        txtmkt.setText("");
        txttkt.setText("");
        jdcDOB.setDate(null);

    }
    
    private void jbtnthemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnthemMouseClicked
        // TODO add your handling code here:
        try{
        KhoaThiBLL bus = new KhoaThiBLL();
            txtmkt.setText(bus.remindKhoathiID());
            bus.docDuLieu();
            KhoaThiDTO khoathi = new KhoaThiDTO();
            if(txttkt.getText().equals("Nhập tên khóa thi")||jdcDOB.getDate().equals("Nhập Ngày bắt đầu")) 
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin Nhân viên cần thêm mới!","Thông báo",0);
            else{
                khoathi.setKhoathiid(Integer.parseInt(txtmkt.getText()));
                khoathi.setNgaybatdau(jdcDOB.getDate());
                khoathi.setTenkhoathi(txttkt.getText());
                            Vector head = new Vector();
                            head.add(khoathi.getKhoathiid());
                            DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                            head.add(format.format(khoathi.getNgaybatdau()));
                            head.add(khoathi.getTenkhoathi());;
                            int rs = bus.them(khoathi);
                            if (rs == 1) {
                                table.addRow(head);
                                jt1.setModel(table);
                                JOptionPane.showMessageDialog(null, "Thêm thành công");
                            } else {
                                JOptionPane.showMessageDialog(null, "Mã đã tồn tại. Thêm thất bại");
                            }
                            cleanView();
                        }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(KhoaThiDTO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnthemMouseClicked

    private void jbnttimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbnttimkiemMouseClicked
        // TODO add your handling code here:
        Map<String,String> map = new HashMap<>();
        map.put("ten_khoa", txtSortTNV.getText());
        doDuLieuSearch(map);
    }//GEN-LAST:event_jbnttimkiemMouseClicked

    private void jbtnxoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnxoaMouseClicked
        // TODO add your handling code here:
        int i = jt1.getSelectedRow();
        if (i >= 0) {
            int result = JOptionPane.showConfirmDialog(null, "Xác nhận xóa ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                KhoaThiBLL bll = new KhoaThiBLL();
                int check = bll.xoa(i);
                if (check == 1) {
                    table.removeRow(i);
                    jt1.setModel(table);
                    JOptionPane.showMessageDialog(null, "Xóa thành công");

                }
                cleanView();
            }
        }
    }//GEN-LAST:event_jbtnxoaMouseClicked

    private void jbtnsuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnsuaMouseClicked
        // TODO add your handling code here:
        KhoaThiBLL bll = new KhoaThiBLL();
        int i = jt1.getSelectedRow();
        if (i >= 0) {

            int result = JOptionPane.showConfirmDialog(null, "Xác nhận sửa ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                KhoaThiDTO khoathi = new KhoaThiDTO();
                khoathi.setKhoathiid(Integer.parseInt(txtmkt.getText()));
                khoathi.setNgaybatdau(jdcDOB.getDate());
                khoathi.setTenkhoathi(txttkt.getText());
                DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                int check = bll.sua(i, khoathi);
                if (check == 1) {
                    table.setValueAt(khoathi.getTenkhoathi(), i,1);
                    table.setValueAt(format.format(khoathi.getNgaybatdau()), i, 2);
                    jt1.setModel(table);
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                }
                cleanView();
            }
        }
    }//GEN-LAST:event_jbtnsuaMouseClicked

    private void jt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt1MouseClicked
        // TODO add your handling code here:
        int i = jt1.getSelectedRow();
        if (i >= 0)
            setTextFields(jt1.getValueAt(i, 0).toString(), jt1.getValueAt(i, 2).toString(), jt1.getValueAt(i, 1).toString());
    }//GEN-LAST:event_jt1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbnttimkiem;
    private javax.swing.JButton jbtnql;
    private javax.swing.JButton jbtnsua;
    private javax.swing.JButton jbtnthem;
    private javax.swing.JButton jbtnxoa;
    private com.toedter.calendar.JDateChooser jdcDOB;
    private javax.swing.JScrollPane jt;
    private javax.swing.JTable jt1;
    private javax.swing.JTextField txtSortTNV;
    private javax.swing.JTextField txtmkt;
    private javax.swing.JTextField txttkt;
    // End of variables declaration//GEN-END:variables
}
