/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.NavigationBUS;
import DTO.ListDTO;
import java.util.ArrayList;


/**
 *
 * @author ADMIN
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
     initComponents();
        NavigationBUS nav = new NavigationBUS(jPnCon);
        nav.setView(tourjPanel, TourjLabel);
        ArrayList<ListDTO> listItem = new ArrayList<>();
        listItem.add (new ListDTO ("thisinh", thisinhJp,thisinhjl));
        listItem.add (new ListDTO ("khoathi", khoathijp,khoathijl));
        listItem.add (new ListDTO ("phongthi", phongthijp,phongthijl));
        listItem.add (new ListDTO ("phieudangky", LTjPanel,TKjLabel1));
        listItem.add (new ListDTO ("timkiem", TKjPanel5,TKjLabel));
        nav.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        thisinhJp = new javax.swing.JPanel();
        thisinhjl = new javax.swing.JLabel();
        phongthijp = new javax.swing.JPanel();
        phongthijl = new javax.swing.JLabel();
        khoathijp = new javax.swing.JPanel();
        khoathijl = new javax.swing.JLabel();
        TKjPanel5 = new javax.swing.JPanel();
        TKjLabel = new javax.swing.JLabel();
        LTjPanel = new javax.swing.JPanel();
        TKjLabel1 = new javax.swing.JLabel();
        jPnCon = new javax.swing.JPanel();
        tourjPanel = new javax.swing.JPanel();
        TourjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(81, 13, 39));

        thisinhJp.setBackground(new java.awt.Color(125, 21, 59));
        thisinhJp.setForeground(new java.awt.Color(153, 153, 0));

        thisinhjl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thisinhjl.setForeground(new java.awt.Color(153, 153, 0));
        thisinhjl.setText("Quản lý Thí sinh");

        javax.swing.GroupLayout thisinhJpLayout = new javax.swing.GroupLayout(thisinhJp);
        thisinhJp.setLayout(thisinhJpLayout);
        thisinhJpLayout.setHorizontalGroup(
            thisinhJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thisinhJpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(thisinhjl)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        thisinhJpLayout.setVerticalGroup(
            thisinhJpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thisinhJpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thisinhjl, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        phongthijp.setBackground(new java.awt.Color(125, 21, 59));
        phongthijp.setForeground(new java.awt.Color(153, 153, 0));

        phongthijl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phongthijl.setForeground(new java.awt.Color(153, 153, 0));
        phongthijl.setText("Quản lý phòng thi");

        javax.swing.GroupLayout phongthijpLayout = new javax.swing.GroupLayout(phongthijp);
        phongthijp.setLayout(phongthijpLayout);
        phongthijpLayout.setHorizontalGroup(
            phongthijpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phongthijpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phongthijl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        phongthijpLayout.setVerticalGroup(
            phongthijpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phongthijpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phongthijl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        khoathijp.setBackground(new java.awt.Color(125, 21, 59));

        khoathijl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        khoathijl.setForeground(new java.awt.Color(153, 153, 0));
        khoathijl.setText("Quản lý khóa thi");

        javax.swing.GroupLayout khoathijpLayout = new javax.swing.GroupLayout(khoathijp);
        khoathijp.setLayout(khoathijpLayout);
        khoathijpLayout.setHorizontalGroup(
            khoathijpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khoathijpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(khoathijl)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        khoathijpLayout.setVerticalGroup(
            khoathijpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khoathijpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(khoathijl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TKjPanel5.setBackground(new java.awt.Color(125, 21, 59));
        TKjPanel5.setForeground(new java.awt.Color(153, 153, 0));

        TKjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TKjLabel.setForeground(new java.awt.Color(153, 153, 0));
        TKjLabel.setText("Tìm kiêm");

        javax.swing.GroupLayout TKjPanel5Layout = new javax.swing.GroupLayout(TKjPanel5);
        TKjPanel5.setLayout(TKjPanel5Layout);
        TKjPanel5Layout.setHorizontalGroup(
            TKjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TKjPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(TKjLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        TKjPanel5Layout.setVerticalGroup(
            TKjPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TKjPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TKjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LTjPanel.setBackground(new java.awt.Color(125, 21, 59));

        TKjLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TKjLabel1.setForeground(new java.awt.Color(153, 153, 0));
        TKjLabel1.setText("Phiếu đăng ký thi");

        javax.swing.GroupLayout LTjPanelLayout = new javax.swing.GroupLayout(LTjPanel);
        LTjPanel.setLayout(LTjPanelLayout);
        LTjPanelLayout.setHorizontalGroup(
            LTjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LTjPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TKjLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        LTjPanelLayout.setVerticalGroup(
            LTjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LTjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TKjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPnConLayout = new javax.swing.GroupLayout(jPnCon);
        jPnCon.setLayout(jPnConLayout);
        jPnConLayout.setHorizontalGroup(
            jPnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPnConLayout.setVerticalGroup(
            jPnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        tourjPanel.setBackground(new java.awt.Color(103, 17, 49));

        TourjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TourjLabel.setForeground(new java.awt.Color(153, 153, 0));
        TourjLabel.setText("Quản lý TTNN");

        javax.swing.GroupLayout tourjPanelLayout = new javax.swing.GroupLayout(tourjPanel);
        tourjPanel.setLayout(tourjPanelLayout);
        tourjPanelLayout.setHorizontalGroup(
            tourjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tourjPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(TourjLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        tourjPanelLayout.setVerticalGroup(
            tourjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tourjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TourjLabel)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(tourjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(thisinhJp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phongthijp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(khoathijp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TKjPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(LTjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276))))
            .addComponent(jPnCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(khoathijp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tourjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phongthijp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(thisinhJp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LTjPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TKjPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPnCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LTjPanel;
    private javax.swing.JLabel TKjLabel;
    private javax.swing.JLabel TKjLabel1;
    private javax.swing.JPanel TKjPanel5;
    private javax.swing.JLabel TourjLabel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnCon;
    private javax.swing.JLabel khoathijl;
    private javax.swing.JPanel khoathijp;
    private javax.swing.JLabel phongthijl;
    private javax.swing.JPanel phongthijp;
    private javax.swing.JPanel thisinhJp;
    private javax.swing.JLabel thisinhjl;
    private javax.swing.JPanel tourjPanel;
    // End of variables declaration//GEN-END:variables
}
